import "./globals.css";
import { I18nProvider } from "../lib/i18n";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <I18nProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased px-4 sm:px-6 lg:px-8`}
        >
          <div className="mx-auto w-full max-w-screen-2xl">
            {children}
          </div>
        </body>
      </html>
    </I18nProvider>
  );
}
