-- AlterTable
ALTER TABLE "public"."Farmer" ADD COLUMN     "acreage" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "batches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bio" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "certifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "gallery" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "image" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "lastHarvest" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "methods" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "region" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "since" INTEGER NOT NULL DEFAULT 2000;
